const Assets = {
  ic_filter: require('../assets/ic_filter.png'),
  img_vegan: require('../assets/img_vegan.png'),
  img_healthy: require('../assets/img_healthy.png'),
  img_banner: require('../assets/img_banner.png'),
  ic_search: require('../assets/ic_search.png'),
  ic_notification: require('../assets/ic_notification.png'),
  bg_pattern: require('../assets/bg_pattern.png'),
  img_logo: require('../assets/img_logo.png'),
  img_onboard02: require('../assets/img_onboard02.png'),
  img_onboard03: require('../assets/img_onboard03.png'),
  bg_pattern_login: require('../assets/bg_pattern_login.png'),
  ic_facebook: require('../assets/ic_facebook.png'),
  ic_google: require('../assets/ic_google.png'),
  ic_profile: require('../assets/ic_profile.png'),
  ic_message: require('../assets/ic_message.png'),
  ic_lock: require('../assets/ic_lock.png'),
  ic_show: require('../assets/ic_show.png'),
  ic_check: require('../assets/ic_check.png'),
  bg_pattern_03: require('../assets/bg_pattern_03.png'),
  ic_back: require('../assets/ic_back.png'),
  ic_pin: require('../assets/ic_pin.png'),
  logo_success: require('../assets/logo_success.png'),
  ic_gallery: require('../assets/ic_gallery.png'),
  ic_camera: require('../assets/ic_camera.png'),
  img_preview: require('../assets/img_preview.png'),
  ic_close: require('../assets/ic_close.png'),
  ic_sms: require('../assets/ic_sms.png'),
  ic_email: require('../assets/ic_email.png'),
  ic_paypal: require('../assets/ic_paypal.png'),
  ic_visa: require('../assets/ic_visa.png'),
  ic_payoneer: require('../assets/ic_payoneer.png'),
  ic_dot: require('../assets/ic_dot.png'),
  ic_show_on: require('../assets/ic_show_on.png'),
  ic_show_off: require('../assets/ic_show_off.png'),
  img_profile: require('../assets/img_profile.png'),
  ic_edit: require('../assets/ic_edit.png'),
  ic_voucher: require('../assets/ic_voucher.png'),
  img_menu: require('../assets/img_menu.png'),
  img_profile_1: require('../assets/img_profile_1.png'),
  img_profile_2: require('../assets/img_profile_2.png'),
  img_profile_3: require('../assets/img_profile_3.png'),
};

export default Assets;
